
	<div class="contentpage">
		<div class="row">
			<div id="widget">
				<div class="header">
					<p>	
						<i class="fas fa-user fnt"></i>
						<span>Class Schedule</span>
					</p>			
				</div>
				<div class="widgetcontent">
					<table>
						<tr>
							<th>Day/Time</th>
							<th>Monday</th>
							<th>Tuesday</th>
							<th>Wednesday</th>
							<th>Thursday</th>
							<th>Friday</th>
							<th>Saturday</th>
						</tr>
						<tr>
							<th><span>7:40-8:40</span></th>
							<td><span>Math</span></td>
							<td><span>Math</span></td>
							<td><span>Math</span></td>
							<td><span>Math</span></td>
							<td><span>Math</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>8:40-9:40</span></th>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>9:40-10:00</span></th>
							<td><span>RECESS</span></td>
							<td><span>RECESS</span></td>
							<td><span>RECESS</span></td>
							<td><span>RECESS</span></td>
							<td><span>RECESS</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>10:00-11:00</span></th>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>11:00-12:00</span></th>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>12:00-1:00</span></th>
							<td><span>LUNCH</span></td>
							<td><span>LUNCH</span></td>
							<td><span>LUNCH</span></td>
							<td><span>LUNCH</span></td>
							<td><span>LUNCH</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>1:00-2:00</span></th>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>2:00-3:00</span></th>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>3:00-4:00</span></th>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span></span></td>
						</tr>
						<tr>
							<th><span>4:00-5:00</span></th>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span>English</span></td>
							<td><span></span></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>